### ISSUE TITLE
Crash on Mac (presumably due to multiprocessing)

### ISSUE THREAD

**Issue by patricknraanes** [Climdyn/qgs#10]
Hi!

Unfortunately I could not run the model on my Mac (MacOS Catalina). I don't have access right now to a Linux system, but I'm guessing it's a Mac-compatibility thing. In my experience, python code that works on Linux tends to work on Mac, but I recently had an issue due to multiprocessing/matplotlib/Mac that proves it is not always the case.

I realise providing Mac support might not be very high among your priorities, but maybe there could be an option to turn off multiprocessing?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pat/Dropbox/DPhil/CoRea/qgs/qgs_rp.py", line 89, in <module>
    integrator.set_func(f)
  File "/Users/pat/Dropbox/DPhil/CoRea/qgs/qgs/integrators/integrator.py", line 169, in set_func
    self.start()
  File "/Users/pat/Dropbox/DPhil/CoRea/qgs/qgs/integrators/integrator.py", line 146, in start
    process.start()
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    raise RuntimeError('''
  File "/Users/pat/anaconda3/envs/qgs/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    exitcode = _main(fd, parent_sentinel)
```

**Comment by jodemaey** [comment]
Yeah that's because 'spawn' is the default multiprocessing start method in python 3.8, while it is 'fork' for Linux. See [here](https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods) for the details and [here](https://bugs.python.org/issue33725) for the (delightful) explanation on why the two OS have different start methods.

This is the main reason why support is difficult for different OS. I thought qgs was finally working for MacOS with Python 3.8 since I had several reports that it was, but apparently it isn't. Thanks for the report.
I'm gonna try to fix this one asap when I get a Mac computer in my hands.

One way to avoid this is to avoid the modules using multiprocessing, e.g. avoid symbolic inner products module (`qgs/inner_products/symbolic.py`) and the integrators (`qgs/integrators/integrator.py`). Normally, if you don't use advanced features (using symbolic basis functions for the inner products) and integrate the model with another integration routine, it should work.

To integrate the model with another integration routine, you can consider the `diffeqpy` package (see for instance this [example](https://qgs.readthedocs.io/en/latest/files/examples/diffeq.html)) or the low-level integration routine in the integrate module (`qgs/integrators/integrate.py`, see [here](https://qgs.readthedocs.io/en/latest/files/technical/integrators.html#integrate-module) for its documentation). The integrate module does the same as the integrator module, it is just a single-process function-based version, which means however that if you want to compute an ensemble, all the members will be computed on the same core.

I hope to be able to solve this issue in the meantime.

**Comment by jodemaey** [comment]
Hi Patrick,

I need a bit more information to solve this issue. Did you get this error while running one of the scripts inside the base folder (`qgs_rp.py` or `qgs_maooam.py`) ?

If so, can you try to run the example notebooks in the `notebooks` folder to see if they work?

I have tested on Windows and I get the same error as you with these scripts ('spawn' is also the default mode on Windows), but on the other hand the Jupyter notebooks work.

If you confirm this, I may have a solution for this problem. Thanks.

**Comment by patricknraanes** [comment]
I get it running `qgs_rp.py`.  The notebooks seem to run fine, no problem!

**Comment by jodemaey** [comment]
Hi Patrick,

I have changed the scripts and it should work now. Could you checkout the branch `multiproc_fix` ([link](https://github.com/Climdyn/qgs/tree/multiproc_fix)) and try to start the scripts `qgs_rp.py` and `qgs_maooam.py` ? 

If it works for you then I'm going to do a PR  and merge.

**Comment by patricknraanes** [comment]
I can confirm it works now 🥳

**Comment by jodemaey** [comment]
Hi Patrick,
Thanks for your report again, qgs is now deemed "compatible" with Windows and MacOS.
Jonathan.
